{
 "title": "LeatherSense",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Actuators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "WITH TypesList AS (\n    SELECT \"actuator_locker\" AS type\n    UNION ALL\n    SELECT \"actuator_fans\" AS type\n    UNION ALL\n    SELECT \"actuator_pump\" AS type\n    UNION ALL\n    SELECT \"actuator_alarm\" AS type\n)\nSELECT \n    REPLACE(tl.type, \"actuator_\", \"\") AS \"Name\", \n    COALESCE(a.status, \"Not found yet\") AS \"Value\"\nFROM \n    TypesList tl\nLEFT JOIN \n    leathersense.actuator a ON tl.type = a.type\nLIMIT 50;\n"
    }
   ]
  },
  {
   "title": "Water characteristics",
   "type": "gauge",
   "description": "The Water Characteristics Monitoring Panel provides a clear, real-time view of the essential parameters of the water used in tanning processes:\npH: Indicates the acidity or alkalinity of the water. An optimal pH level is crucial for the correct chemical reactions during leather tanning.\nSalinity: Measures the concentration of dissolved salts in the water, expressed in degrees Baumé. Accurate control of salinity is fundamental for the consistency and quality of the final product.\nTemperature: Shows the water temperature. Keeping the temperature within specified limits is essential to prevent alterations in chemical processes and ensure operational safety.",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "WITH WaterCharacteristics AS (\n    SELECT 'pH' AS type\n    UNION ALL\n    SELECT 'Salinity' AS type\n    UNION ALL\n    SELECT 'Temperature' AS type\n),\nRecentTelemetry AS (\n    SELECT \n        t.type,\n        t.value,\n        t.timestamp,\n        ROW_NUMBER() OVER (PARTITION BY t.type ORDER BY t.timestamp DESC) AS rn\n    FROM\n        telemetry t\n    WHERE\n        t.timestamp >= NOW() - INTERVAL 12 HOUR\n)\nSELECT \n    COALESCE(rt.type, wc.type) as Name,\n    rt.value AS Value,\n    0 AS Min,\n    COALESCE(p.min, 0) AS T1,\n    p.max as T2\nFROM\n    WaterCharacteristics wc\nLEFT JOIN \n    parameter p ON wc.type = p.type\nLEFT JOIN\n    (SELECT \n        type, value \n     FROM \n        RecentTelemetry \n     WHERE \n        rn = 1) rt \nON wc.type = rt.type;\n"
    }
   ]
  },
  {
   "title": "Toxic Gas Detection",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "select type, value\nfrom leathersense.telemetry\nwhere type = \"H2S\" and timestamp >= NOW() - INTERVAL 12 hour\norder by id desc\nlimit 1;"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "SELECT \n    type, \n    timestamp, \n    value AS Value,\n    (SELECT AVG(value) \n     FROM leathersense.telemetry \n     WHERE type = \"pH\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Mean,\n    (SELECT MIN(value) \n     FROM leathersense.telemetry \n     WHERE type = \"pH\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Min,\n    (SELECT MAX(value) \n     FROM leathersense.telemetry \n     WHERE type = \"pH\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Max\nFROM \n    leathersense.telemetry\nWHERE \n    type = \"pH\"\n    AND timestamp >= NOW() - INTERVAL 12 HOUR\nORDER BY \n    timestamp;\n"
    }
   ]
  },
  {
   "title": "Salinity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "° Baumé" } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "SELECT \n    type, \n    timestamp, \n    value AS Value,\n    (SELECT AVG(value) \n     FROM leathersense.telemetry \n     WHERE type = \"salinity\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Mean,\n    (SELECT MIN(value) \n     FROM leathersense.telemetry \n     WHERE type = \"salinity\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Min,\n    (SELECT MAX(value) \n     FROM leathersense.telemetry \n     WHERE type = \"salinity\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Max\nFROM \n    leathersense.telemetry\nWHERE \n    type = \"salinity\"\n    AND timestamp >= NOW() - INTERVAL 12 HOUR\nORDER BY \n    timestamp;\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "SELECT \n    type, \n    timestamp, \n    value AS Value,\n    (SELECT AVG(value) \n     FROM leathersense.telemetry \n     WHERE type = \"temperature\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Mean,\n    (SELECT MIN(value) \n     FROM leathersense.telemetry \n     WHERE type = \"temperature\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Min,\n    (SELECT MAX(value) \n     FROM leathersense.telemetry \n     WHERE type = \"temperature\"\n       AND timestamp >= NOW() - INTERVAL 12 HOUR) AS Max\nFROM \n    leathersense.telemetry\nWHERE \n    type = \"temperature\"\n    AND timestamp >= NOW() - INTERVAL 12 HOUR\nORDER BY \n    timestamp;\n"
    }
   ]
  },
  {
   "title": "Toxic Gas Production",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "dataset": "leathersense",
     "rawSql": "select timestamp, value\nfrom leathersense.telemetry\nWHERE type = \"H2S\" and timestamp >= NOW() - INTERVAL 12 HOUR\nORDER BY timestamp;"
    }
   ]
  }
 ]
}